<p align="center"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Senac_logo.svg/1280px-Senac_logo.svg.png" width="200"></p>

# Big Data

# Técnicas de Processamento e Análise de Big Data

## Aula 2 - Análise e Visualização de Dados - Parte 1 - Numpy - Lista de Exercícios

# NumPy Exercises 

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
arr5 = np.ones(10)*5
arr5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [9]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

array([ 0.41332137])

In [23]:
np.random.rand(1)

array([0.54309091])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

array([ 0.53110144, -0.94058694,  0.55386733, -0.34476631, -0.22358063,
        0.99567816, -1.01628384,  1.19451035, -0.03688856, -1.7418426 ,
       -0.70855335, -0.96934949, -0.25128579, -0.12924384, -0.19962742,
        0.2068274 ,  0.70750409, -1.20188965, -1.24592649,  0.23852376,
       -1.01860068,  0.27355025,  0.38869352,  2.96183039,  0.10793186])

In [24]:
np.random.randn(25)

array([ 0.83478435, -1.24598753,  0.43472586, -0.88910884,  1.47209497,
        0.41331319,  0.81086494,  0.44295492, -0.78380996,  0.27710374,
       -2.28101211, -0.65372117, -1.67073258, -2.53496169, -0.38556303,
       -1.20041259, -0.2936047 ,  0.02930443, -0.1682262 , -0.36797403,
        0.74645788, -1.70787258, -1.86675068,  1.88504306,  0.55941565])

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Create the following matrix:

In [140]:
np.arange(0,1,100)

array([0])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [56]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
arr_2d = arr.reshape(5,5)+1
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE



array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [70]:
arr_2d[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE



20

In [73]:
arr_2d[3,4]

20

In [19]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE



array([[ 2],
       [ 7],
       [12]])

In [120]:
arr_2d[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE



array([21, 22, 23, 24, 25])

In [128]:
arr_2d[4]

array([21, 22, 23, 24, 25])

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE



array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [132]:
arr_2d[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

In [135]:
np.sum(arr_2d)

325

#### Get the standard deviation of the values in mat

7.2111025509279782

In [136]:
np.std(arr_2d)

7.211102550927978

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

In [139]:
np.sum(arr_2d,axis=0)

array([55, 60, 65, 70, 75])